# Generated by Django 4.0.5 on 2022-10-23 15:23

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('ArtID', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=300)),
                ('image_url', models.URLField()),
                ('type', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('ArtistID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('profile_img_url', models.URLField()),
                ('about', models.TextField(max_length=300)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('profile_img_url', models.URLField()),
                ('about', models.TextField(max_length=300)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('rating', models.FloatField()),
                ('comment', models.TextField(max_length=300)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.art')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.customer')),
            ],
        ),
        migrations.AddField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.artist'),
        ),
    ]
