# Generated by Django 4.0.5 on 2022-12-14 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='artId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.art'),
        ),
        migrations.AlterField(
            model_name='review',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.art'),
        ),
    ]
