# Generated by Django 4.0.5 on 2022-12-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_date_order_odate_order_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='artist',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='App.artist'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='App.customer'),
        ),
    ]
