# Generated by Django 4.0.5 on 2022-10-24 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='profile_img_url',
        ),
        migrations.AddField(
            model_name='artist',
            name='profile_pic',
            field=models.ImageField(default='avatar.png', upload_to='Profile'),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
