# Generated by Django 4.0.5 on 2022-12-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_order_artist_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='cname',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='crole',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='croleid',
            field=models.IntegerField(default=0),
        ),
    ]
