# Generated by Django 4.0.5 on 2022-10-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_artist_profile_img_url_artist_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_img_url',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='avatar.png', upload_to='Profile'),
        ),
    ]
