# Generated by Django 4.0.5 on 2022-12-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_art_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='', max_length=300),
        ),
    ]
