# Generated by Django 4.0.5 on 2022-10-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_artist_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
