# Generated by Django 4.0.5 on 2022-12-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='showRev',
            field=models.BooleanField(default=False),
        ),
    ]
