# Generated by Django 4.0.5 on 2022-12-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_artist_country_alter_customer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='art',
            name='image_url',
            field=models.ImageField(default='default.jpeg', upload_to='Art'),
        ),
    ]
