# Generated by Django 4.0.5 on 2022-12-04 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_art_title_alter_art_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='year',
        ),
        migrations.AddField(
            model_name='art',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
