# Generated by Django 4.0.5 on 2022-12-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_remove_art_year_art_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image_url',
            field=models.ImageField(default='Art/default.jpeg', upload_to='Art'),
        ),
    ]
