# Generated by Django 4.0.5 on 2022-12-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_art_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_pic',
            field=models.ImageField(default='Profile/avatar.png', upload_to='Profile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='Profile/avatar.png', upload_to='Profile'),
        ),
    ]
